// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperTutor.Contexts.Profiles.Persistence;

#nullable disable

namespace SuperTutor.Contexts.Profiles.Persistence.Migrations
{
    [DbContext(typeof(ProfilesDbContext))]
    partial class ProfilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("profiles")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuperTutor.Contexts.Profiles.Domain.StudentProfiles.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StudyGrade")
                        .HasColumnType("int");

                    b.Property<string>("studySubjects")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("StudySubjects");

                    b.HasKey("Id");

                    b.ToTable("StudentProfiles", "profiles");
                });

            modelBuilder.Entity("SuperTutor.Contexts.Profiles.Domain.TutorProfiles.Models.Entities.RedactionComments.TutorProfileRedactionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("CreatedByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SettledByAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SettledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TutorProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TutorProfileId");

                    b.ToTable("TutorProfileRedactionComments", "profiles");
                });

            modelBuilder.Entity("SuperTutor.Contexts.Profiles.Domain.TutorProfiles.TutorProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastApprovalAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastApprovalDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastRedactionRequestAdminId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastRedactionRequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RateForOneHour")
                        .HasPrecision(19, 4)
                        .HasColumnType("decimal(19,4)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TutoringSubject")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tutoringGrades")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TutoringGrades");

                    b.HasKey("Id");

                    b.ToTable("TutorProfiles", "profiles");
                });

            modelBuilder.Entity("SuperTutor.Contexts.Profiles.Domain.TutorProfiles.Models.Entities.RedactionComments.TutorProfileRedactionComment", b =>
                {
                    b.HasOne("SuperTutor.Contexts.Profiles.Domain.TutorProfiles.TutorProfile", null)
                        .WithMany("RedactionComments")
                        .HasForeignKey("TutorProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SuperTutor.Contexts.Profiles.Domain.TutorProfiles.TutorProfile", b =>
                {
                    b.Navigation("RedactionComments");
                });
#pragma warning restore 612, 618
        }
    }
}
