// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperTutor.Contexts.Payments.Infrastructure.Shared.Persistence;

#nullable disable

namespace SuperTutor.Contexts.Payments.Infrastructure.Shared.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    [Migration("20220605080307_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuperTutor.Contexts.Payments.Application.Transfers.Queries.TransferQueryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ChargeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TutorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Transfers", "payments");
                });

            modelBuilder.Entity("SuperTutor.Contexts.Payments.Infrastructure.Tutors.Persistence.Models.TutorQuery.TutorQueryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AreTermsOfServiceAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("AreVerificationDocumentsCollected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAddressInformationCollected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBankAccountInformationCollected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonalInformationCollected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tutors", "payments");
                });
#pragma warning restore 612, 618
        }
    }
}
