// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperTutor.Contexts.Payments.Infrastructure.Shared.Persistence;

#nullable disable

namespace SuperTutor.Contexts.Payments.Infrastructure.Shared.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SuperTutor.Contexts.Payments.Infrastructure.Tutors.Persistence.Models.TutorQuery.TutorQueryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AreTermsOfServiceAccepted")
                        .HasColumnType("bit");

                    b.Property<bool>("AreVerificationDocumentsCollected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAddressInformationCollected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBankAccountInformationCollected")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPersonalInformationCollected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Tutors", "payments");
                });
#pragma warning restore 612, 618
        }
    }
}
