version: '3.4'

services:
    supertutor-apigateway-web:
        container_name: supertutor-apigateway-web
        image: zdraffko/supertutor:apigateway-web
        build:
            context: .
            dockerfile: ./ApiGateways/SuperTutor.ApiGateways.Web/Dockerfile
        environment:
            - Elasticsearch__Urls=http://supertutor-elasticsearch-node-1:9200
            - Elasticsearch__Username=${ELASTIC_DEFAULT_USERNAME}
            - Elasticsearch__Password=${ELASTIC_DEFAULT_PASSWORD}
            - ApiUrls__Identity=http://supertutor-identity/api
            - ApiUrls__Payments=http://supertutor-payments/api
            - ApiUrls__Profiles=http://supertutor-profiles/api
            - AuthTokenSecretKey=${AUTH_TOKEN_SECRET_KEY}
        volumes:
            - ./.aspnet/apigateway-web/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
            - /var/log/supertutor/apigateway-web:/app/logs
        ports: 
            - 4000:80
        restart: on-failure
        networks:
            - supertutor-infrastructure_default

    supertutor-identity:
        container_name: supertutor-identity
        image: zdraffko/supertutor:identity
        build:
            context: .
            dockerfile: ./Contexts/Identity/SuperTutor.Contexts.Identity.Startup/Dockerfile
        environment:
            - Database__ConnectionString=Server=supertutor-mssqlserver;Database=SuperTutorIdentity;User Id=sa;Password=${MSSQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true
            - Elasticsearch__Urls=http://supertutor-elasticsearch-node-1:9200
            - Elasticsearch__Username=${ELASTIC_DEFAULT_USERNAME}
            - Elasticsearch__Password=${ELASTIC_DEFAULT_PASSWORD}
            - RabbitMq__Url=amqp://${RABBITMQ_DEFAULT_USERNAME}:${RABBITMQ_DEFAULT_PASSWORD}@supertutor-rabbitmq:5672
            - AuthToken__SecretKey=${AUTH_TOKEN_SECRET_KEY}
        volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
            - /var/log/supertutor/identity:/app/logs
        ports: 
            - 5000:80
        restart: on-failure
        networks:
            - supertutor-infrastructure_default

    supertutor-profiles:
        container_name: supertutor-profiles
        image: zdraffko/supertutor:profiles
        build:
            context: .
            dockerfile: ./Contexts/Profiles/SuperTutor.Contexts.Profiles.Startup/Dockerfile
        environment:
            - Database__ConnectionString=Server=supertutor-mssqlserver;Database=SuperTutorProfiles;User Id=sa;Password=${MSSQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true
            - Elasticsearch__Urls=http://supertutor-elasticsearch-node-1:9200
            - Elasticsearch__Username=${ELASTIC_DEFAULT_USERNAME}
            - Elasticsearch__Password=${ELASTIC_DEFAULT_PASSWORD}
            - RabbitMq__Url=amqp://${RABBITMQ_DEFAULT_USERNAME}:${RABBITMQ_DEFAULT_PASSWORD}@supertutor-rabbitmq:5672
        volumes:
            - ./.aspnet/profiles/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
            - /var/log/supertutor/profiles:/app/logs
        ports: 
            - 5001:80
        restart: on-failure
        networks:
            -  supertutor-infrastructure_default

    supertutor-catalog:
        container_name: supertutor-catalog
        image: zdraffko/supertutor:catalog
        build:
            context: .
            dockerfile: ./Contexts/Catalog/SuperTutor.Contexts.Catalog.Startup/Dockerfile
        environment:
            - Database__ConnectionString=Server=supertutor-mssqlserver;Database=SuperTutorCatalog;User Id=sa;Password=${MSSQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true
            - Elasticsearch__Urls=http://supertutor-elasticsearch-node-1:9200
            - Elasticsearch__Username=${ELASTIC_DEFAULT_USERNAME}
            - Elasticsearch__Password=${ELASTIC_DEFAULT_PASSWORD}
            - RabbitMq__Url=amqp://${RABBITMQ_DEFAULT_USERNAME}:${RABBITMQ_DEFAULT_PASSWORD}@supertutor-rabbitmq:5672
        volumes:
            - ./.aspnet/catalog/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
            - /var/log/supertutor/catalog:/app/logs
        ports: 
            - 5002:80
        restart: on-failure
        networks:
            -  supertutor-infrastructure_default

    supertutor-schedule:
        container_name: supertutor-schedule
        image: zdraffko/supertutor:schedule
        build:
            context: .
            dockerfile: ./Contexts/Schedule/SuperTutor.Contexts.Schedule.Startup/Dockerfile
        environment:
            - EventStore__Url=esdb://supertutor-eventstore:2113?tls=false&keepAliveTimeout=10000&keepAliveInterval=10000
            - Elasticsearch__Urls=http://supertutor-elasticsearch-node-1:9200
            - Elasticsearch__Username=${ELASTIC_DEFAULT_USERNAME}
            - Elasticsearch__Password=${ELASTIC_DEFAULT_PASSWORD}
            - RabbitMq__Url=amqp://${RABBITMQ_DEFAULT_USERNAME}:${RABBITMQ_DEFAULT_PASSWORD}@supertutor-rabbitmq:5672
        volumes:
            - ./.aspnet/schedule/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
            - /var/log/supertutor/schedule:/app/logs
        ports: 
            - 5003:80
        restart: on-failure
        networks:
            -  supertutor-infrastructure_default

    supertutor-classrooms:
        container_name: supertutor-classrooms
        image: zdraffko/supertutor:classrooms
        build:
            context: .
            dockerfile: ./Contexts/Classrooms/SuperTutor.Contexts.Classrooms.Startup/Dockerfile
        environment:
            - Database__ConnectionString=Server=supertutor-mssqlserver;Database=SuperTutorClassrooms;User Id=sa;Password=${MSSQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true
            - Elasticsearch__Urls=http://supertutor-elasticsearch-node-1:9200
            - Elasticsearch__Username=${ELASTIC_DEFAULT_USERNAME}
            - Elasticsearch__Password=${ELASTIC_DEFAULT_PASSWORD}
            - RabbitMq__Url=amqp://${RABBITMQ_DEFAULT_USERNAME}:${RABBITMQ_DEFAULT_PASSWORD}@supertutor-rabbitmq:5672
            - AuthTokenSecretKey=${AUTH_TOKEN_SECRET_KEY}
        volumes:
            - ./.aspnet/classrooms/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
            - /var/log/supertutor/classrooms:/app/logs
        ports: 
            - 5004:80
        restart: on-failure
        networks:
            - supertutor-infrastructure_default

    supertutor-payments:
        container_name: supertutor-payments
        image: zdraffko/supertutor:payments
        build:
            context: .
            dockerfile: ./Contexts/Payments/SuperTutor.Contexts.Payments.Startup/Dockerfile
        environment:
            - Database__ConnectionString=Server=supertutor-mssqlserver;Database=SuperTutorPayments;User Id=sa;Password=${MSSQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true
            - EventStore__Url=esdb://supertutor-eventstore:2113?tls=false&keepAliveTimeout=10000&keepAliveInterval=10000
            - Elasticsearch__Urls=http://supertutor-elasticsearch-node-1:9200
            - Elasticsearch__Username=${ELASTIC_DEFAULT_USERNAME}
            - Elasticsearch__Password=${ELASTIC_DEFAULT_PASSWORD}
            - RabbitMq__Url=amqp://${RABBITMQ_DEFAULT_USERNAME}:${RABBITMQ_DEFAULT_PASSWORD}@supertutor-rabbitmq:5672
            - Stripe__SecretKey=${STRIPE_SECRET_KEY}
        volumes:
            - ./.aspnet/payments/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
            - /var/log/supertutor/payments:/app/logs
        ports: 
            - 5005:80
        restart: on-failure
        networks:
            -  supertutor-infrastructure_default

networks:
    supertutor-infrastructure_default:
        external: true
