version: '3.4'

services:
    supertutor-mssqlserver:
        container_name: supertutor-mssqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=devPass123!
        volumes: 
            - supertutor-mssqlserver-volume:/var/opt/mssql
        networks: 
            - supertutor-network
        ports:
            - "1433:1433"

    supertutor-rabbitmq:
        container_name: supertutor-rabbitmq
        image: rabbitmq:3-management
        hostname: supertutor-rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USERNAME}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASSWORD}
        volumes:
            - supertutor-rabbitmq-valume:/var/lib/rabbitmq/mnesia
        networks: 
            - supertutor-network
        ports:
            - 5672:5672
            - 15672:15672

    elasticsearch:
        container_name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.0.0
        ports:
            - 9200:9200
        volumes:
            - supertutor-elasticsearch-volume:/usr/share/elasticsearch/data
        environment:
            - ES_JAVA_OPTS=-Xms512m -Xmx512m
            - discovery.type=single-node
            - xpack.license.self_generated.type=basic
        networks:
            - supertutor-network
  
    supertutor-kibana:
        container_name: supertutor-kibana
        image: docker.elastic.co/kibana/kibana:8.0.0
        ports:
            - 5601:5601
        depends_on:
            - elasticsearch
        environment:
            - ELASTICSEARCH_URL=http://elasticsearch:9200
            - ELASTICSEARCH_USERNAME=kibana_system
            - ELASTICSEARCH_PASSWORD=${KIBANA_SYSTEM_USER_PASSWORD}
        networks:
            - supertutor-network
    
    supertutor-identity:
        container_name: supertutor-identity
        image: zdraffko/supertutor:identity
        build:
            context: .
            dockerfile: ./Contexts/Identity/SuperTutor.Contexts.Identity.Startup/Dockerfile
        environment:
            - Database__ConnectionString=Server=supertutor-mssqlserver;Database=SuperTutorIdentity;User Id=sa; Password=${MSSQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true
            - Elasticsearch__Url=http://elasticsearch:9200
            - Elasticsearch__Username=${ELASTIC_DEFAULT_USERNAME}
            - Elasticsearch__Password=${ELASTIC_DEFAULT_PASSWORD}
            - RabbitMq__Url=amqp://${RABBITMQ_DEFAULT_USERNAME}:${RABBITMQ_DEFAULT_PASSWORD}@supertutor-rabbitmq:5672
        volumes:
            - ./.aspnet/identity/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - supertutor-network
        ports: 
            - 5000:80
        restart: on-failure
        depends_on:
            - supertutor-mssqlserver
            - supertutor-rabbitmq

    supertutor-profiles:
        container_name: supertutor-profiles
        image: zdraffko/supertutor:profiles
        build:
            context: .
            dockerfile: ./Contexts/Profiles/SuperTutor.Contexts.Profiles.Startup/Dockerfile
        environment:
            - Database__ConnectionString=Server=supertutor-mssqlserver;Database=SuperTutorProfiles;User Id=sa; Password=${MSSQLSERVER_SA_PASSWORD};MultipleActiveResultSets=true
            - Elasticsearch__Url=http://elasticsearch:9200
            - Elasticsearch__Username=${ELASTIC_DEFAULT_USERNAME}
            - Elasticsearch__Password=${ELASTIC_DEFAULT_PASSWORD}
            - RabbitMq__Url=amqp://${RABBITMQ_DEFAULT_USERNAME}:${RABBITMQ_DEFAULT_PASSWORD}@supertutor-rabbitmq:5672
        volumes:
            - ./.aspnet/profiles/DataProtection-Keys:/root/.aspnet/DataProtection-Keys
        networks: 
            - supertutor-network
        ports: 
            - 5001:80
        restart: on-failure
        depends_on:
            - supertutor-mssqlserver
            - supertutor-rabbitmq

volumes:
    supertutor-mssqlserver-volume:
    supertutor-rabbitmq-valume:
    supertutor-elasticsearch-volume:

networks:
    supertutor-network:
